apiVersion: v1
kind: Pod
metadata:
  name: node-selector-demo-1
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
  nodeSelector:
    demo: naminglaebls
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoExecute"   # It can be NoSchedule or NoExecute or NoExecute
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule" 